package com.jailedbird.wired.lib_compiler.utils

@Suppress("SpellCheckingInspection")
object Consts {
    // Generate
    private const val SEPARATOR = "$$"
    const val PROJECT = "Wired"
    const val TAG = "$PROJECT::"
    const val WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY Wired"
    const val METHOD_INJECT = "inject"
    const val NAME_OF_WIRED = SEPARATOR + PROJECT + SEPARATOR + "Autowired"

    // System interface
    const val ACTIVITY = "android.app.Activity"
    const val ACTIVITY_ANDROIDX = "androidx.appcompat.app.AppCompatActivity"
    const val FRAGMENT = "android.app.Fragment"
    const val FRAGMENT_V4 = "android.support.v4.app.Fragment"
    const val FRAGMENT_ANDROIDX = "androidx.fragment.app.Fragment"

    // Kotlin type
    private const val KOTLIN = "kotlin"
    const val KBYTE = "$KOTLIN.Byte"
    const val KSHORT = "$KOTLIN.Short"
    const val KINTEGER = "$KOTLIN.Int"
    const val KLONG = "$KOTLIN.Long"
    const val KFLOAT = "$KOTLIN.Float"
    const val KDOUBEL = "$KOTLIN.Double"
    const val KBOOLEAN = "$KOTLIN.Boolean"
    const val KCHAR = "$KOTLIN.Char"
    const val KSTRING = "$KOTLIN.String"
    const val PARCELABLE = "android.os.Parcelable"
    const val SERIALIZABLE = "java.io.Serializable"
}